'use client';
import { useEffect, useRef, useState } from 'react';
import { Sparkles, Hand, Grid2X2, SlidersHorizontal, Volume2, VolumeX, Lock, Check } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { Switch } from '@/components/ui/switch';
const skins = [
 {name:'Original nothing',color:'#b3a0f8',cost:0,glyph:'✳'},
 {name:'Peach of mind',color:'#ffb49e',cost:25,glyph:'✿'},
 {name:'Certified pickle',color:'#b4d99a',cost:75,glyph:'✦'},
 {name:'Blue on purpose',color:'#96c9ed',cost:150,glyph:'❋'},
 {name:'Forbidden custard',color:'#edcf72',cost:300,glyph:'✺'},
 {name:'The final whatever',color:'#eda7cc',cost:500,glyph:'❖'}];
const remarks = ['Excellent. Absolutely nothing happened.','A tiny victory for absolutely no reason.','Somewhere, a spoon is proud of you.','Still no purpose. Remarkable form, though.','You have a real talent for this.','The universe has declined to comment.'];
export default function Home(){
 const [count,setCount]=useState(0),[skin,setSkin]=useState(0),[sound,setSound]=useState(false),[haptics,setHaptics]=useState(true),[ready,setReady]=useState(false),[saved,setSaved]=useState(true),[combo,setCombo]=useState(0),[pop,setPop]=useState(0),[message,setMessage]=useState(remarks[0]);
 const last=useRef(0), comboRef=useRef(0),countRef=useRef(0),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),audio=useRef<AudioContext|null>(null);
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem('one-more-boop-v1')||'{}');const n=Number.isSafeInteger(s.count)&&s.count>=0?s.count:0;setCount(n);countRef.current=n;setSkin(Number.isInteger(s.skin)&&skins[s.skin]?.cost<=n?s.skin:0);setSound(s.sound===true);setHaptics(s.haptics!==false);}catch{setSaved(false);}setReady(true);return()=>{clearTimeout(timer.current);void audio.current?.close();};},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('one-more-boop-v1',JSON.stringify({count,skin,sound,haptics}));}catch{setSaved(false);}},[count,skin,sound,haptics,ready]);
 function boop(){if(!ready)return;const now=Date.now();comboRef.current=now-last.current<650?comboRef.current+1:1;last.current=now;setCombo(comboRef.current);clearTimeout(timer.current);timer.current=setTimeout(()=>{setCombo(0);comboRef.current=0;},1100);const n=++countRef.current;setCount(n);setPop(v=>v+1);const unlock=skins.find(s=>s.cost===n);setMessage(unlock?`Unlocked: ${unlock.name}! Find it in your collection.`:remarks[Math.floor(n/7)%remarks.length]);if(haptics&&navigator.vibrate)navigator.vibrate(12);if(sound)try{audio.current||=new AudioContext();const a=audio.current;void a.resume();const o=a.createOscillator(),g=a.createGain();o.frequency.setValueAtTime(320+(comboRef.current%8)*55,a.currentTime);o.frequency.exponentialRampToValueAtTime(130,a.currentTime+.13);g.gain.setValueAtTime(.16,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.17);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.18);o.onended=()=>{o.disconnect();g.disconnect();};}catch{setSound(false);}}
 const toolState=useRef({count,skin,ready});toolState.current={count,skin,ready};
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'equip_boop_style',description:'Equip an unlocked button style, indexed 0 through 5.',inputSchema:{type:'object',properties:{index:{type:'integer',minimum:0,maximum:5}},required:['index'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const i=(input as {index?:number})?.index;const current=toolState.current;if(!current.ready||!Number.isInteger(i)||i===undefined||!skins[i]||skins[i].cost>current.count)throw new Error('Style is locked or invalid.');setSkin(i);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {equipped:skins[i].name};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 const next=skins.find(s=>s.cost>count),unlocked=skins.filter(s=>s.cost<=count).length,title=count>=500?'Supreme Nothingness':count>=150?'Director of Boops':count>=25?'Certified Booper':'Amateur Nothing-doer';
 return <main className="shell" style={{'--boop-color':skins[skin].color} as React.CSSProperties}>
 <header className="topbar"><a href="/" className="brand"><Sparkles size={23}/><span>one more boop<span className="brand-dot">.</span></span></a><span className="edition">THE POINTLESS LITTLE APP</span><button className="icon-button" onClick={()=>setSound(!sound)} aria-label={sound?'Mute sound':'Enable sound'}>{sound?<Volume2 size={20}/>:<VolumeX size={20}/>}</button></header>
 <Tabs defaultValue="boop"><div className="workspace"><aside className="intro"><span className="eyebrow">ZERO PURPOSE. FULL COMMITMENT.</span><h1>Big button.<br/>Little joy.</h1><p>No winning. No losing.<br/>Just a really good boop.</p><div className="rank"><span className="rank-icon"><Sparkles size={20}/></span><div><small>YOUR VERY UNOFFICIAL TITLE</small><strong>{title}</strong></div></div><div className="aside-note">Made for your thumbs.<br/>And your complete lack of plans.</div></aside>
 <section className="console"><TabsContent value="boop" className="play-panel"><div className="play-top"><span className="eyebrow">LET’S ACCOMPLISH NOTHING</span><span className="live-dot">ready to boop</span></div><div className="counter"><span>{count.toLocaleString()}</span><p>perfectly pointless boops</p></div><div className="button-stage"><span className={`combo ${combo>=3?'visible':''}`}>{combo} in a row · nice rhythm!</span><button id="boop-action" disabled={!ready} onClick={boop} className="boop-button" aria-label="Boop"><span className="button-glyph">{skins[skin].glyph}</span><span>boop</span></button>{pop>0&&<span key={pop} className="pop" aria-hidden="true">+1 ✦</span>}</div><p className="tap-note"><Hand size={16}/>tap. feel something. repeat.</p><p className="reaction" role="status">{message}</p><div className="unlock"><div><span>{next?'A little something for your nothing':'Nothing left to prove'}</span><strong>{next?`${count} / ${next.cost}`:'6 / 6'}</strong></div><Progress aria-label="Next collectible" value={next?count/next.cost*100:100}/><p>{next?<><Lock size={13}/>{next.name} at {next.cost} boops</>:<><Check size={14}/>Every button style is yours. Boop freely.</>}</p></div></TabsContent>
 <TabsContent value="collection" className="collection-panel"><span className="eyebrow">THE MUSEUM OF NOTHING</span><h2>Your little collection<span>{unlocked}/6</span></h2><p>Entirely useless. Entirely yours.</p><div className="skin-grid">{skins.map((s,i)=><button key={s.name} disabled={count<s.cost} onClick={()=>setSkin(i)} className={`skin-card ${skin===i?'selected':''}`} aria-pressed={skin===i}><span className="swatch" style={{background:s.color}}>{count>=s.cost?s.glyph:<Lock size={24}/>}</span><strong>{s.name}</strong><small>{count<s.cost?`${s.cost} boops to unlock`:skin===i?'✓ Equipped':'Tap to equip'}</small></button>)}</div></TabsContent>
 <TabsContent value="settings" className="settings-panel"><span className="eyebrow">FINE-TUNE YOUR NOTHING</span><h2>Good little details.</h2><label className="setting"><span><strong>Sound effects</strong><small>A soft pop with every boop.</small></span><Switch checked={sound} onCheckedChange={setSound}/></label><label className="setting"><span><strong>Haptic taps</strong><small>A tiny buzz, where your device supports it.</small></span><Switch checked={haptics} onCheckedChange={setHaptics}/></label><div className="settings-note"><Sparkles/><h3>All the joy. Zero homework.</h3><p>Your collection stays on this browser. No account, no streaks to keep alive, and no notifications. Come back whenever.</p><p>On your phone, use your browser’s menu to add this app to your home screen.</p></div></TabsContent>
 <TabsList className="bottom-nav"><TabsTrigger value="boop"><Hand/>Boop</TabsTrigger><TabsTrigger value="collection"><Grid2X2/>Collection <span className="badge">{unlocked}</span></TabsTrigger><TabsTrigger value="settings"><SlidersHorizontal/>Settings</TabsTrigger></TabsList></section></div></Tabs><footer><span>100% effort. 0% productivity.</span><span>{saved?'Your nothing is saved on this device.':'Storage unavailable. Progress lasts this session.'}</span></footer></main>;
}
